name: Generate binaries and create a Release on merge

on:
  workflow_dispatch:
  push: 
    branches: ["main", "master"]

jobs:
  export_assetripper_cli:
    runs-on: ${{ matrix.os }}
    permissions: write-all
    name: Export AssetRipper.CLI ${{ matrix.runtime }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            ext: ""
          - os: windows-latest
            runtime: win-x64
            ext: ".exe"
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore Source/AssetRipper.CLI/AssetRipper.CLI.csproj

    - name: Build
      run: dotnet build Source/AssetRipper.CLI/AssetRipper.CLI.csproj --no-restore --configuration Release

    - name: Publish self-contained binary
      run: |
        dotnet publish Source/AssetRipper.CLI/AssetRipper.CLI.csproj \
          --no-restore \
          --configuration Release \
          --runtime ${{ matrix.runtime }} \
          --self-contained true \
          /p:PublishSingleFile=true \
          --output ./publish-${{ matrix.runtime }}
    
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: publish-${{ matrix.runtime }}/AssetRipper.CLI${{ matrix.ext }}
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     - name: Publish binaries
#       run: dotnet publish Source/AssetRipper.CLI/AssetRipper.CLI.csproj --no-restore --configuration Release --output ./publish --self-contained --runtime ${{ matrix.runtime }} /p:PublishSingleFile=true 
# #/p:PublishTrimmed=true

  #   - name: Archive binaries
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: AssetRipper_CLI_${{ matrix.runtime }}
  #       path: ./publish

  # create_release:
  #   needs: export_assetripper_cli
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Create release
  #     uses: ncipollo/release-action@v1.12.0
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       artifacts: ${{ steps.export.outputs.archive_directory }}/*
  #       tag: "nightly"
  #       generateReleaseNotes: true
  #       makeLatest: true
  #       allowUpdates: true
