name: Generate binaries and create a Release on merge

on:
  workflow_dispatch:
  push: 
    branches: ["main", "master"]

jobs:
  export_assetripper_cli:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export AssetRipper.CLI
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: windows-latest
            runtime: win-x64
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore Source/AssetRipper.CLI/AssetRipper.CLI.csproj

    - name: Build
      run: dotnet build Source/AssetRipper.CLI/AssetRipper.CLI.csproj --no-restore --configuration Release

    - name: Publish binaries
      run: dotnet publish Source/AssetRipper.CLI/AssetRipper.CLI.csproj --no-restore --configuration Release --output ./publish --self-contained --runtime ${{ matrix.runtime }} /p:PublishSingleFile=true 
#/p:PublishTrimmed=true

    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: AssetRipper_CLI_${{ matrix.runtime }}
        path: ./publish

  create_release:
    needs: export_assetripper_cli
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
        tag: "nightly"
        generateReleaseNotes: true
        makeLatest: true
        allowUpdates: true
